export const GET_LOCATIONS = 'GET_LOCATIONS';
export const GET_MOVIE_DETAILS = 'GET_MOVIE_DETAILS';
export const FETCH_MOVIES = 'FETCH_MOVIES';
export const FETCH_MOVIES_LOADING = 'FETCH_MOVIES_LOADING';

export const GEOCODE_PROGRESS_RESET = 'GEOCODE_PROGRESS_RESET';
export const GEOCODE_PROGRESS_UPDATE = 'GEOCODE_PROGRESS_UPDATE';

