export const GET_POPULAR_MOVIES = 'GET_POPULAR_MOVIES';
export const GET_POPULAR_MOVIES_LOADING = 'GET_POPULAR_MOVIES_LOADING';
export const GET_LOCATIONS = 'GET_LOCATIONS';
export const GET_POSTER = 'GET_POSTER';
export const FETCH_MOVIES = 'FETCH_MOVIES';
export const FETCH_MOVIES_LOADING = 'FETCH_MOVIES_LOADING';

